CC=gcc
CFLAGS=-g -Wall -std=c99
TARGETS=q1 q2 q3
all: $(TARGETS)
q1: q1.c
	$(CC) $(CFLAGS) -o $@ $@.c
q2: q2.c
	$(CC) $(CFLAGS) -o $@ $@.c
q3: q3.c
	$(CC) $(CFLAGS) -o $@ $@.c
clean:
	rm -rf *.o *~ $(TARGETS)


